### ISSUE TITLE
Not sure how to host my own instance...

### ISSUE THREAD

**Issue by JDJGInc** [bluntano/discord-midi-player#2]

**Comment by JDJGInc** [comment]
I mainly need this to be fixed so I can host on my raspberry pi, thank you :D

**Comment by bluntano** [comment]
sorry for absence and lack of communication. i'll get onto it once im free from conscription service if not manage to get it done before that (no promises)

**Comment by JDJGInc** [comment]
thank you :D

**Comment by bluntano** [comment]
so good news: i finally was able to get some time and also had progress with dockerizing the bot with database, so you could run it anywhere as long as you have docker installed on your system. hopefully ill be able to implement it in coming week.

**Comment by bluntano** [comment]
Hey!

Sorry it took me so long. So, i ended up dockerizing the entire bot meaning, you would only need Docker installed with Docker Compose in your system, whether it be Linux, Windows, macOS, etc. [Here's the commit itself I did](https://github.com/bluntano/discord-midi-player/commit/d44af0e285ae05a39cbd8048ab38a440a7854f89).

_I also tested the solution beforehand on my Windows laptop (tested, worked). And on my Raspberry Pi Zero W (Raspbian) it failed because, there's no MongoDB Docker image for `arm32v6`_
