### ISSUE TITLE
Issue while deploying on Raspberry Pi Zero.

### ISSUE THREAD

**Issue by osctorand** [bluntano/discord-midi-player#4]
Docker gives error message "ERROR: no matching manifest for linux/arm/v6 in the manifest list entries" when attempting to deploy on a Raspberry Pi Zero.

**Comment by bluntano** [comment]
Sorry for late answer!

Since RPi Zero has 32-bit CPU, the newest MongoDB you could install would be 2.x. I've also stumbled across to that issue and that's why you can't install the newest MongoDB on Zero or Zero W module.

You'd need to change `docker-compose.yml` file and add a tag at the end of the image you want to get in `image` property. As an example:
```
...
  mongo:
          container_name: mongo
          image: mongo:2.8.0
...
```

That's in the case you want to set up MongoDB locally next to the bot itself.
